"""empty message

Revision ID: 01f042c1bc14
Revises: 60879ce249b1
Create Date: 2026-01-26 22:45:21.997695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f042c1bc14'
down_revision: Union[str, Sequence[str], None] = '60879ce249b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_views_listing_constraint', 'listing_views', ['listing_id', 'viewer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_views_listing_constraint', 'listing_views', type_='unique')
    # ### end Alembic commands ###
