"""empty message

Revision ID: 227b46fe1997
Revises: db56ce03adf7
Create Date: 2025-12-25 13:23:04.631019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227b46fe1997'
down_revision: Union[str, Sequence[str], None] = 'db56ce03adf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_views', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_views', 'created_at')
    # ### end Alembic commands ###
