"""empty message

Revision ID: 4da78392cb73
Revises: b5d5485e54f7
Create Date: 2025-12-28 19:24:16.413982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da78392cb73'
down_revision: Union[str, Sequence[str], None] = 'b5d5485e54f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_chat_participant_constraint', 'chat_participants', ['chat', 'participant'])
    op.add_column('user_reviews', sa.Column('seller', sa.Integer(), nullable=False))
    op.add_column('user_reviews', sa.Column('listing', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_author_seller_constraint', 'user_reviews', ['author', 'seller'])
    op.create_foreign_key(None, 'user_reviews', 'listings', ['listing'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_reviews', 'users', ['seller'], ['id'], ondelete='CASCADE')
    op.alter_column('verify_codes', 'field_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verify_codes', 'field_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'user_reviews', type_='foreignkey')
    op.drop_constraint(None, 'user_reviews', type_='foreignkey')
    op.drop_constraint('unique_author_seller_constraint', 'user_reviews', type_='unique')
    op.drop_column('user_reviews', 'listing')
    op.drop_column('user_reviews', 'seller')
    op.drop_constraint('unique_chat_participant_constraint', 'chat_participants', type_='unique')
    # ### end Alembic commands ###
