"""empty message

Revision ID: 4db5b3c31894
Revises: 7791e884745a
Create Date: 2026-01-10 11:47:15.403440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db5b3c31894'
down_revision: Union[str, Sequence[str], None] = '7791e884745a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reviews', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_reviews', 'created_at')
    # ### end Alembic commands ###
