"""empty message

Revision ID: 60879ce249b1
Revises: f45eff6ce86a
Create Date: 2026-01-24 21:19:24.752387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60879ce249b1'
down_revision: Union[str, Sequence[str], None] = 'f45eff6ce86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.Enum('CHANGE_PASSWORD', 'CHANGE_EMAIL', 'VERIFICATION', name='verificationcodesoperationtypes'), nullable=False),
    sa.Column('field_value', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('safe_transactions')
    op.drop_table('verify_codes')
    op.add_column('chat_messages', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('chat_messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chat_messages_author_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_chat_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'author')
    op.drop_column('chat_messages', 'chat')
    op.add_column('chat_participants', sa.Column('participant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('unique_chat_participant_constraint'), 'chat_participants', type_='unique')
    op.create_unique_constraint('unique_chat_participant_constraint', 'chat_participants', ['chat_id', 'participant_id'])
    op.drop_constraint(op.f('chat_participants_participant_fkey'), 'chat_participants', type_='foreignkey')
    op.create_foreign_key(None, 'chat_participants', 'users', ['participant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_participants', 'participant')
    op.add_column('chats', sa.Column('listing_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chats_listing_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chats', 'listing')
    op.add_column('listing_favorite', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('listing_favorite', sa.Column('listing_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('unique_user_listing_constraint'), 'listing_favorite', type_='unique')
    op.create_unique_constraint('unique_user_listing_constraint', 'listing_favorite', ['user_id', 'listing_id'])
    op.drop_constraint(op.f('listing_favorite_listing_fkey'), 'listing_favorite', type_='foreignkey')
    op.drop_constraint(op.f('listing_favorite_user_fkey'), 'listing_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'listing_favorite', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'listing_favorite', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('listing_favorite', 'user')
    op.drop_column('listing_favorite', 'listing')
    op.alter_column('listing_media', 'url',
               existing_type=sa.VARCHAR(),
               comment='Path to the file',
               existing_nullable=False)
    op.add_column('listing_views', sa.Column('listing_id', sa.Integer(), nullable=False))
    op.add_column('listing_views', sa.Column('viewer_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('listing_views_listing_fkey'), 'listing_views', type_='foreignkey')
    op.drop_constraint(op.f('listing_views_viewer_fkey'), 'listing_views', type_='foreignkey')
    op.create_foreign_key(None, 'listing_views', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'listing_views', 'users', ['viewer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('listing_views', 'listing')
    op.drop_column('listing_views', 'viewer')
    op.add_column('listings', sa.Column('publisher_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('listings_publisher_fkey'), 'listings', type_='foreignkey')
    op.create_foreign_key(None, 'listings', 'users', ['publisher_id'], ['id'], ondelete='CASCADE')
    op.drop_column('listings', 'publisher')
    op.add_column('reviews', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('listing_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('unique_author_seller_constraint'), 'reviews', type_='unique')
    op.create_unique_constraint('unique_author_seller_constraint', 'reviews', ['author_id', 'seller_id'])
    op.drop_constraint(op.f('reviews_author_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_listing_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_seller_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'seller')
    op.drop_column('reviews', 'listing')
    op.drop_column('reviews', 'author')
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='Path to the file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='Path to the file')
    op.add_column('reviews', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('listing', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('seller', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_seller_fkey'), 'reviews', 'users', ['seller'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_listing_fkey'), 'reviews', 'listings', ['listing'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_author_fkey'), 'reviews', 'users', ['author'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_author_seller_constraint', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('unique_author_seller_constraint'), 'reviews', ['author', 'seller'], postgresql_nulls_not_distinct=False)
    op.drop_column('reviews', 'listing_id')
    op.drop_column('reviews', 'seller_id')
    op.drop_column('reviews', 'author_id')
    op.add_column('listings', sa.Column('publisher', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key(op.f('listings_publisher_fkey'), 'listings', 'users', ['publisher'], ['id'], ondelete='CASCADE')
    op.drop_column('listings', 'publisher_id')
    op.add_column('listing_views', sa.Column('viewer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listing_views', sa.Column('listing', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listing_views', type_='foreignkey')
    op.drop_constraint(None, 'listing_views', type_='foreignkey')
    op.create_foreign_key(op.f('listing_views_viewer_fkey'), 'listing_views', 'users', ['viewer'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('listing_views_listing_fkey'), 'listing_views', 'listings', ['listing'], ['id'], ondelete='CASCADE')
    op.drop_column('listing_views', 'viewer_id')
    op.drop_column('listing_views', 'listing_id')
    op.alter_column('listing_media', 'url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Path to the file',
               existing_nullable=False)
    op.add_column('listing_favorite', sa.Column('listing', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listing_favorite', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listing_favorite', type_='foreignkey')
    op.drop_constraint(None, 'listing_favorite', type_='foreignkey')
    op.create_foreign_key(op.f('listing_favorite_user_fkey'), 'listing_favorite', 'users', ['user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('listing_favorite_listing_fkey'), 'listing_favorite', 'listings', ['listing'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_user_listing_constraint', 'listing_favorite', type_='unique')
    op.create_unique_constraint(op.f('unique_user_listing_constraint'), 'listing_favorite', ['user', 'listing'], postgresql_nulls_not_distinct=False)
    op.drop_column('listing_favorite', 'listing_id')
    op.drop_column('listing_favorite', 'user_id')
    op.add_column('chats', sa.Column('listing', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_listing_fkey'), 'chats', 'listings', ['listing'], ['id'], ondelete='CASCADE')
    op.drop_column('chats', 'listing_id')
    op.add_column('chat_participants', sa.Column('participant', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.create_foreign_key(op.f('chat_participants_participant_fkey'), 'chat_participants', 'users', ['participant'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_chat_participant_constraint', 'chat_participants', type_='unique')
    op.create_unique_constraint(op.f('unique_chat_participant_constraint'), 'chat_participants', ['chat_id', 'participant'], postgresql_nulls_not_distinct=False)
    op.drop_column('chat_participants', 'participant_id')
    op.add_column('chat_messages', sa.Column('chat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_chat_fkey'), 'chat_messages', 'chats', ['chat'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_messages_author_fkey'), 'chat_messages', 'users', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'chat_id')
    op.drop_column('chat_messages', 'author_id')
    op.create_table('verify_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operation_type', postgresql.ENUM('CHANGE_PASSWORD', 'CHANGE_EMAIL', 'VERIFICATION', name='verifycodesoperationtypes'), autoincrement=False, nullable=False),
    sa.Column('field_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('verify_codes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('verify_codes_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('verify_codes_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('safe_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('listing', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buyer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_payment_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_seller_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_buyer_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_transaction_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_transaction_on_hold', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer'], ['users.id'], name=op.f('safe_transactions_buyer_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing'], ['listings.id'], name=op.f('safe_transactions_listing_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller'], ['users.id'], name=op.f('safe_transactions_seller_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('safe_transactions_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('safe_transactions_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
