"""empty message

Revision ID: 8668685af304
Revises: 4db5b3c31894
Create Date: 2026-01-10 11:54:15.380174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8668685af304'
down_revision: Union[str, Sequence[str], None] = '4db5b3c31894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('listing', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name=op.f('user_reviews_author_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing'], ['listings.id'], name=op.f('user_reviews_listing_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller'], ['users.id'], name=op.f('user_reviews_seller_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_reviews_pkey')),
    sa.UniqueConstraint('author', 'seller', name=op.f('unique_author_seller_constraint'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('uuid', name=op.f('user_reviews_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
