"""empty message

Revision ID: 9c97f1eb70be
Revises: 4da78392cb73
Create Date: 2025-12-30 11:49:56.116438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c97f1eb70be'
down_revision: Union[str, Sequence[str], None] = '4da78392cb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('unique_chat_participant_constraint'), 'chat_participants', type_='unique')
    op.create_unique_constraint('unique_chat_participant_constraint', 'chat_participants', ['chat_id', 'participant'])
    op.drop_constraint(op.f('chat_participants_chat_fkey'), 'chat_participants', type_='foreignkey')
    op.create_foreign_key(None, 'chat_participants', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_participants', 'chat')
    op.create_unique_constraint('unique_user_listing_constraint', 'listing_favorite', ['user', 'listing'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_listing_constraint', 'listing_favorite', type_='unique')
    op.add_column('chat_participants', sa.Column('chat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.create_foreign_key(op.f('chat_participants_chat_fkey'), 'chat_participants', 'chats', ['chat'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_chat_participant_constraint', 'chat_participants', type_='unique')
    op.create_unique_constraint(op.f('unique_chat_participant_constraint'), 'chat_participants', ['chat', 'participant'], postgresql_nulls_not_distinct=False)
    op.drop_column('chat_participants', 'chat_id')
    # ### end Alembic commands ###
