"""empty message

Revision ID: b5d5485e54f7
Revises: 227b46fe1997
Create Date: 2025-12-28 15:41:25.485938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d5485e54f7'
down_revision: Union[str, Sequence[str], None] = '227b46fe1997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_oauth', sa.Boolean(), nullable=False))
    op.add_column('verify_codes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('verify_codes_user_fkey'), 'verify_codes', type_='foreignkey')
    op.create_foreign_key(None, 'verify_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('verify_codes', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verify_codes', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'verify_codes', type_='foreignkey')
    op.create_foreign_key(op.f('verify_codes_user_fkey'), 'verify_codes', 'users', ['user'], ['id'], ondelete='CASCADE')
    op.drop_column('verify_codes', 'user_id')
    op.drop_column('users', 'is_oauth')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
