"""empty message

Revision ID: d86b3d21fce7
Revises: 9c97f1eb70be
Create Date: 2025-12-30 19:15:23.992821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86b3d21fce7'
down_revision: Union[str, Sequence[str], None] = '9c97f1eb70be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('uuid', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'chat_messages', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='unique')
    op.drop_column('chat_messages', 'uuid')
    # ### end Alembic commands ###
