"""empty message

Revision ID: db56ce03adf7
Revises: c00095da6e41
Create Date: 2025-12-25 13:08:22.434327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db56ce03adf7'
down_revision: Union[str, Sequence[str], None] = 'c00095da6e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('publisher', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('is_price_negotiable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['publisher'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('verify_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.Enum('CHANGE_PASSWORD', 'CHANGE_EMAIL', 'VERIFICATION', name='verifycodesoperationtypes'), nullable=False),
    sa.Column('field_value', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('listing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('listing_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('listing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing', sa.Integer(), nullable=False),
    sa.Column('viewer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safe_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('listing', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.Integer(), nullable=False),
    sa.Column('seller', sa.Integer(), nullable=False),
    sa.Column('is_payment_completed', sa.Boolean(), nullable=False),
    sa.Column('is_seller_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_buyer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_transaction_completed', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('is_transaction_on_hold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['buyer'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.Column('participant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_participants')
    op.drop_table('chat_messages')
    op.drop_table('safe_transactions')
    op.drop_table('listing_views')
    op.drop_table('listing_media')
    op.drop_table('listing_favorite')
    op.drop_table('chats')
    op.drop_table('verify_codes')
    op.drop_table('listings')
    # ### end Alembic commands ###
