"""empty message

Revision ID: fd3f0aa05259
Revises: d86b3d21fce7
Create Date: 2025-12-31 22:38:33.044663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3f0aa05259'
down_revision: Union[str, Sequence[str], None] = 'd86b3d21fce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_media', sa.Column('listing_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('listing_media_listing_fkey'), 'listing_media', type_='foreignkey')
    op.create_foreign_key(None, 'listing_media', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.drop_column('listing_media', 'listing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_media', sa.Column('listing', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listing_media', type_='foreignkey')
    op.create_foreign_key(op.f('listing_media_listing_fkey'), 'listing_media', 'listings', ['listing'], ['id'], ondelete='CASCADE')
    op.drop_column('listing_media', 'listing_id')
    # ### end Alembic commands ###
